services:
  api:
    volumes:
      - /volume1/docker/librechat/.env:/app/.env
      - /volume1/docker/librechat/librechat.yaml:/app/librechat.yaml
      - /volume1/docker/librechat/images:/app/client/public/images
      - /volume1/docker/librechat/uploads:/app/uploads
      - /volume1/docker/librechat/logs:/app/logs
      - /volume1/docker/librechat/skill:/app/skill
      - librechat-data:/app/data

  mongodb:
    image: mongo:4.4.18
